# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |this|

  this.vm.define "web" do |web|
    web.vm.box = "ubuntu/focal64"
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "192.168.33.10"
    web.vm.network "forwarded_port", guest: 8000, host: 8000
    web.vm.provider "virtualbox" do |virtualbox|
      virtualbox.name = "web"
    end
  end

end
