---
- name: Configure webserver with nginx
  hosts: localhost
  connection: local
  become: true
  gather_facts: true

  vars:
    conf_file: /etc/nginx/sites-available/default

  tasks:
    - name: Ensure nginx is installed
      ansible.builtin.package:
        name: nginx
        state: present
        update_cache: true

    - name: Copy nginx config file
      ansible.builtin.copy:
        src: playbooks/files/nginx.conf
        dest: "{{ conf_file }}"
        mode: "0644"

    - name: Copy home page template
      ansible.builtin.template:
        src: playbooks/templates/index.html.j2
        dest: /usr/share/nginx/html/index.html
        mode: "0644"

    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
