#!/usr/bin/env ansible-playbook
---

- name: Configure awx
  hosts: all
  become: false
  gather_facts: false

  vars:
    awx_host: "{{ groups.tower[0] }}"
    # yamllint disable-line rule:line-length
    cfg: "-k --conf.host https://{{ awx_host }} --conf.user {{ awx_user | default('admin', true) }}"

  tasks:
    - name: Install collections
      delegate_to: localhost
      run_once: true
      changed_when: true
      # yamllint disable-line rule:line-length
      command: "ansible-galaxy collection install -f -p collections -r roles/requirements.yml"

    - name: Login to Tower
      delegate_to: localhost
      run_once: true
      no_log: true
      changed_when: false
      command: "awx {{ cfg }} --conf.password {{ admin_password }} -k login"
      register: awx_login

    - name: Set awx_token
      delegate_to: localhost
      run_once: true
      set_fact:
        awx_token: "{{ awx_login.stdout | from_json | json_query('token') }}"

    - name: Create ~/.tower_cli.cfg
      delegate_to: localhost
      run_once: true
      template:
        src: tower_cli.cfg
        dest: "~/.tower_cli.cfg"
        mode: 0600
...
