#!/usr/bin/env ansible-playbook
---

- hosts: all:!localhost
  become: true
  gather_facts: true

  pre_tasks:
    - name: Register RHEL 8
      redhat_subscription:
        state: present
        username: "{{ lookup('env','RH_USER') }}"
        password: "{{ lookup('env','RH_PASS') }}"
        syspurpose:
          role: "Red Hat Enterprise Server"
          usage: "Development/Test"
          service_level_agreement: "Self-Support"
      tags:
        - register

  roles:
    - {role: ssh_keys, tags: ssh_keys}

- hosts: tower
  become: true
  gather_facts: true

  roles:
    - {role: aap, tags: aap}

...
