---
# Standards: 0.2
galaxy_info:
  author: Bas Meijer
  description: CICD Demo

  license: All rights reserved

  min_ansible_version: 2.9

  platforms:
    - name: EL
      versions:
        - 8

  galaxy_tags: []

dependencies: []
...
