Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "testserver"
  config.vm.network "forwarded_port",
    id: "ssh", guest: 22, host: 2202, auto_correct: false
  config.vm.network "forwarded_port",
    id: "http", guest: 80, host: 8080
  config.vm.network "forwarded_port",
    id: "https", guest: 443, host: 8443
end
