---
# https://www.ssh-audit.com/hardening_guides.html
# This config removes ssh-rsa host key support
# More info https://www.openssh.com/txt/release-8.2
HostKeyAlgorithms: ssh-ed25519-cert-v01@openssh.com,ssh-ed25519
Ciphers: chacha20-poly1305@openssh.com,aes128-ctr,aes256-ctr,aes192-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
# yamllint disable-line rule:line-length
KexAlgorithms: curve25519-sha256,diffie-hellman-group-exchange-sha256,curve25519-sha256@libssh.org,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512
MACs: umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com
weak_host_keys:
  - ssh_host_rsa_key
  - ssh_host_ecdsa_key
...
