---

- name: Install nginx webserver
  become: true
  apt:
    update_cache: true
    cache_valid_time: 3600
    pkg: nginx

- name: Ensure config path exists
  become: true
  file:
    path: "{{ nginx_conf_path }}"
    state: directory
    mode: 0755
  when: tls_enabled

- name: Create ssl certificates
  become: true
  command: >
    openssl req -new -x509 -nodes -out {{ mezzanine_proj_name }}.crt
    -keyout {{ mezzanine_proj_name }}.key -subj '/CN={{ domains[0] }}' -days 3650
    chdir={{ nginx_conf_path }}
    creates={{ nginx_conf_path }}/{{ mezzanine_proj_name }}.crt
  when: tls_enabled
  notify: Restart nginx

- name: Set the nginx config file
  become: true
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/mezzanine.conf
    mode: 0755
  notify: Restart nginx

- name: Enable the nginx config file
  become: true
  file:
    src: /etc/nginx/sites-available/mezzanine.conf
    dest: /etc/nginx/sites-enabled/mezzanine.conf
    state: link
  notify: Restart nginx

- name: Remove the default nginx config file
  become: true
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx
...
