---

- name: Install Java8
  win_chocolatey:
    name: "{{ jdk_package }}"
    state: present

- name: Set Java_home
  win_environment:
    state: present
    name: JAVA_HOME
    value: "{{ win_java_home }}"
    level: machine

- name: Add Java to path
  win_path:
    elements:
      - "{{ win_java_path }}"

...
