---
- name: Install critical and security updates
  win_updates:
    category_names:
      - CriticalUpdates
      - SecurityUpdates
    state: installed
  register: update_result

- name: Reboot if required
  win_reboot:
  when: update_result.reboot_required
...
