#!/usr/bin/env ansible-playbook
---
- name: Start an EC2 instance from an AMI
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Configure SSH security group
      amazon.aws.ec2_group:
        name: my_security_group
        description: SSH and Web Access
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: '0.0.0.0/0'
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0

    - name: Configure and start EC2 instance
      amazon.aws.ec2_instance:
        name: 'ansiblebook-instance'
        image_id: ami-0984b03a78a0bad40
        instance_type: t2.micro
        key_name: ec2key
        security_group: my_security_group
        network:
          assign_public_ip: true
        tags:
          Name: ansiblebook
          type: web
          env: staging
        volumes:
          - device_name: /dev/sda1
            ebs:
              volume_size: 16
              delete_on_termination: true
      register: instance

    - debug: var=instance
...
