---

- name: Create a logs directory
  file:
    path: "{{ ansible_env.HOME }}/logs"
    state: directory
    mode: 0755

- name: Check out the repository on the host
  git:
    repo: "{{ mezzanine_repo_url }}"
    dest: "{{ mezzanine_proj_path }}"
    version: master
    accept_hostkey: true
    update: false
  tags:
    - repo

- name: Create python3 virtualenv
  pip:
    name:
      - pip
      - wheel
      - setuptools
    state: latest
    virtualenv: "{{ mezzanine_venv_path }}"
    virtualenv_command: /usr/bin/python3 -m venv
  tags:
    - skip_ansible_lint

- name: Copy requirements.txt to home directory
  copy:
    src: "{{ files_src_path | default() }}requirements.txt"
    dest: "{{ mezzanine_reqs_path }}"
    mode: 0644

- name: Install packages listed in requirements.txt
  pip:
    virtualenv: "{{ mezzanine_venv_path }}"
    requirements: "{{ mezzanine_reqs_path }}"
