---

- name: Install Redis slaves
  hosts: all:!localhost
  become: true

  tasks:

    - name: "Create docker network(s)"
      docker_network:
        name: "redis"
        ipam_config:
          - subnet: "10.16.0.0/24"
            gateway: "10.16.0.254"
        state: present
        labels:
          owner: molecule
...
