# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |this|

  # Forward ssh-agent for cloning from Github.com
  this.ssh.forward_agent = true
  # disable updating guest additions
  if Vagrant.has_plugin?("vagrant-vbguest")
    this.vbguest.auto_update = false
  end
  # disable guest additions
  this.vm.synced_folder '.', '/vagrant', disabled: true
  this.vm.define "dev" do |web|
    web.vm.box = "ubuntu/focal64"
    web.vm.hostname = "dev"
    # This IP is used in the playbook
    web.vm.network "private_network", ip: "192.168.56.10"
    web.vm.network "forwarded_port", guest: 80, host: 8000
    web.vm.network "forwarded_port", guest: 443, host: 8443
    web.vm.provider "virtualbox" do |virtualbox|
      virtualbox.name = "dev"
    end
  end
  this.vm.define "prod" do |web|
    web.vm.box = "ubuntu/focal64"
    web.vm.hostname = "prod"
    # This IP is used in the playbook
    web.vm.network "private_network", ip: "192.168.56.11"
    web.vm.network "forwarded_port", guest: 80, host: 9000
    web.vm.network "forwarded_port", guest: 443, host: 9443
    web.vm.provider "virtualbox" do |virtualbox|
      virtualbox.name = "prod"
    end
  end
end
