---
version: '2'
services:
  nginx:
    image: bbaassssiiee/nginx-ghost
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ${PWD}/certs:/certs
    links:
      - ghost
  ghost:
    image: ghost
    environment:
      NODE_ENV: development
...
