#!/usr/bin/env ansible-playbook
---
- name: Run Ghost locally
  hosts: localhost
  gather_facts: false
  vars:
    ansible_python_interpreter: ../py3/bin/python
  tasks:

    - name: Create Nginx image
      docker_image:
        build:
          path: ./nginx
        source: build
        name: bbaassssiiee/nginx-ghost
        state: present
        force_source: "{{ force_source | default(false) }}"
        tag: "{{ tag | default('v1') }}"

    - name: Create certs directory
      file:
        path: "./certs"
        state: directory
        mode: 0750

    - name: Create certs
      command: >
        openssl req -new -x509 -nodes
        -out certs/nginx.crt -keyout certs/nginx.key
        -subj '/CN=localhost' -days 365
      args:
        creates: certs/nginx.crt

    - name: Bring up services
      docker_compose:
        project_src: .
        state: present
...
