---

- name: Ensure group developers
  win_group:
    name: developers

- name: Ensure ansible user exists
  win_user:
    name: ansible
    password: '%4UJ[nLbQz*:BJ%9gV|x'
    groups: developers
    password_expired: true
    groups_action: add

- name: Manage tools directory
  win_file:
    path: 'C:/Tools'
    state: directory

- name: Manage Features
  win_feature:
    name: "{{ item }}"
    state: absent
  loop: "{{ windows_features_remove }}"

- name: Manage IIS Web-Server with sub features and management tools
  win_feature:
    name: Web-Server
    state: present
    include_sub_features: true
    include_management_tools: true
  register: win_iis_feature

- name: Reboot if installing Web-Server feature requires it
  win_reboot:
  when: win_iis_feature.reboot_required
...
