# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |this|

  this.vm.define "web" do |web|
    web.vm.box = "ubuntu/focal64"
    web.vm.hostname = "web"
    web.vm.network "forwarded_port", guest: 8000, host: 8000
    web.vm.provider "virtualbox" do |virtualbox|
      virtualbox.name = "web"
    end
  end

  # provision the VM with a shell script
  this.vm.provision "shell", path: "./mezzanine-dev.sh"
  this.vm.provision "shell", inline: "echo Now open http://127.0.0.1:8000/"
end
