#!/usr/bin/env ansible-playbook
---
- name: Deploy ssh
  hosts: all
  strategy: free
  debugger: on_failed
  roles:
    - role: ssh
      crypto_settings: 'faster.yml'
      tags: ssh
  tasks:
    - name: Display hostvars
      debug: var=hostvars[inventory_hostname]

- name: Deploy postgres on db
  hosts: db
  debugger: on_failed
  vars_files:
    - secrets.yml

  roles:
    - role: database
      tags: database
      database_name: "{{ mezzanine_proj_name }}"
      database_user: "{{ mezzanine_proj_name }}"

- name: deploy mezzanine on web
  hosts: web
  debugger: on_unreachable
  vars_files:
    - secrets.yml

  roles:
    - role: mezzanine
      tags: mezzanine
      database_host: "{{ hostvars.db.ansible_enp0s8.ipv4.address }}"
    - role: nginx
      tags: nginx
...
