---
- name: Install Ansible-lint via pipx
  hosts: localhost
  connection: local
  become: yes
  gather_facts: yes

  tasks:
    - name: Ensure pipx is installed (Debian/Ubuntu)
      when: ansible_os_family == "Debian"
      apt:
        update_cache: yes
        state: present
        name:
          - python3-pip
          - pipx

    - name: Ensure pipx is installed (RedHat/Fedora)
      when: ansible_os_family == "RedHat"
      dnf:
        name:
          - python3-pip
          - python3-pipx
        state: present

    - name: Install ansible-lint via pipx (system-wide)
      ansible.builtin.command: >
        pipx install ansible-lint
        --pip-args='--upgrade'
      environment:
        PIPX_HOME: /usr/local/pipx
        PIPX_BIN_DIR: /usr/local/bin

    - name: Verify ansible-lint installation
      ansible.builtin.command: ansible-lint --version
      register: lint_version

    - name: Show installed ansible-lint version
      debug:
        msg: "Installed {{ lint_version.stdout }}"
