---
- name: Install Vagrant
  hosts: localhost
  connection: local
  become: true
  vars:
    vagrant_version: "2.4.9"
    vagrant_pkg_url_debian: "https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}-1_amd64.deb"
    vagrant_pkg_url_redhat: "https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}-1.x86_64.rpm"

  tasks:
    - name: Ensure dependencies are installed (Debian)
      ansible.builtin.apt:
        name: curl
        state: present
      when: ansible_os_family == "Debian"

    - name: Download Vagrant .deb (Debian)
      ansible.builtin.get_url:
        url: "{{ vagrant_pkg_url_debian }}"
        dest: "/tmp/vagrant.deb"
        mode: '0644'
      when: ansible_os_family == "Debian"

    - name: Install Vagrant .deb (Debian)
      ansible.builtin.apt:
        deb: "/tmp/vagrant.deb"
      when: ansible_os_family == "Debian"

    - name: Download Vagrant .rpm (RedHat)
      ansible.builtin.get_url:
        url: "{{ vagrant_pkg_url_redhat }}"
        dest: "/tmp/vagrant.rpm"
        mode: '0644'
      when: ansible_os_family == "RedHat"

    - name: Install Vagrant .rpm (RedHat)
      ansible.builtin.dnf:
        name: "/tmp/vagrant.rpm"
        state: present
      when: ansible_os_family == "RedHat"

    - name: Verify installation
      ansible.builtin.command: vagrant --version
      register: vagrant_version_output
      changed_when: false

    - name: Show installed Vagrant version
      ansible.builtin.debug:
        msg: "Installed {{ vagrant_version_output.stdout }}"
