---
file:
  "{{ goss_test_directory }}/goss.yaml":
    exists: true
    mode: "0644"
    owner: root
    group: root
    filetype: file
  "{{ goss_dest }}":
    exists: true
    owner: root
    group: root
    mode: "0755"
    sha256: "{{ goss[goss_version].sha256sum }}"
