---

- name: restart nginx
  debug:
    msg: "checking config first"
  changed_when: true
  notify:
    - check nginx configuration
    - restart nginx - after config check
  listen: ssl_certs_changed


- name: reload nginx
  debug:
    msg: "checking config first"
  changed_when: true
  notify:
    - check nginx configuration
    - reload nginx - after config check
  listen: ssl_certs_changed

- name: check nginx configuration
  command: "nginx -t"
  register: result
  changed_when: "result.rc != 0"
  check_mode: false

- name: restart nginx - after config check
  service:
    name: nginx
    state: restarted

- name: reload nginx - after config check
  service:
    name: nginx
    state: reloaded
