---
# Standards: 0.2
galaxy_info:
  role_name: ssh
  namespace: ansiblebook
  author: Bas Meijer
  description: Hardened SSH
  company: dockpack

  license: MIT

  min_ansible_version: 2.11.0

  platforms:
    - name: EL
      versions:
        - 8
  galaxy_tags:
    - system
    - security
    - hardening

dependencies: []
...
