# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Use the same key for each machine
  config.ssh.insert_key = false
  config.ssh.forward_agent = true
  # disable guest additions
  config.vm.synced_folder '.', "/vagrant", disabled: true

  # run provision playbook after booting first time
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision.yml"
    ansible.verbose = ""
    ansible.compatibility_mode = "2.0"
    ansible.host_key_checking = false
  end

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/focal64"
    ubuntu.vm.hostname = "ubuntu.192.168.56.10.nip.io"
    ubuntu.vm.network "private_network", ip: "192.168.56.10"
    ubuntu.vm.provider "virtualbox" do |virtualbox|
      virtualbox.name = "ubuntu"
      virtualbox.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end

  config.vm.define "fedora" do |fedora|
    fedora.vm.box = "fedora/34-cloud-base"
    fedora.vm.hostname = "fedora.192.168.56.11.nip.io"
    fedora.vm.network "private_network", ip: "192.168.56.11"
	  fedora.vm.provider "virtualbox" do |virtualbox|
      virtualbox.name = "fedora"
      virtualbox.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end

  config.vm.define "debian" do |debian|
    debian.vm.box = "debian/buster64"
    debian.vm.hostname = "debian.192.168.56.12.nip.io"
    debian.vm.network "private_network", ip: "192.168.56.12"
	  debian.vm.provider "virtualbox" do |virtualbox|
      virtualbox.name = "debian"
      virtualbox.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end

  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/7"
    centos.vm.hostname = "centos.192.168.56.13.nip.io"
    centos.vm.network "private_network", ip: "192.168.56.13"
	  centos.vm.provider "virtualbox" do |virtualbox|
      virtualbox.name = "centos"
      virtualbox.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end
end
