---

- block:
    - name: Get goss binary on localhost
      become: false
      delegate_to: localhost
      get_url:
        url: "https://github.com/aelsabbahy/goss/releases/download/{{ goss_version }}/goss-linux-amd64"
        checksum: "sha256:{{ goss[goss_version].sha256sum }}"
        validate_certs: false
        dest: "/tmp/goss"
        mode: 0755
      register: network_access
      until: network_access is success
      retries: 10
      delay: 2
      tags:
        - goss

    - name: Ensure we have local copy of goss
      become: false
      delegate_to: localhost
      stat:
        path: /tmp/goss
      register: goss_bin
      tags:
        - goss

    - name: Copy goss to remote
      become: true
      copy:
        src: "/tmp/goss"
        dest: "{{ goss_dest }}"
        owner: "{{ goss_user }}"
        group: "{{ goss_user }}"
        mode: 0755
      when: goss_bin.stat.exists
  when: goss_download == 'localhost'

- name: Get goss binary directly
  become: true
  get_url:
    url: "https://github.com/aelsabbahy/goss/releases/download/{{ goss_version }}/goss-linux-amd64"
    sha256sum: "{{ goss[goss_version].sha256sum }}"
    validate_certs: false
    dest: "{{ goss_dest }}"
    owner: "{{ goss_user }}"
    group: "{{ goss_user }}"
    mode: 0755
  register: network_access
  until: network_access is success
  retries: 10
  delay: 2
  when: goss_download == 'direct'
  tags:
    - goss

- name: "Ensure {{ goss_test_directory }} exists"
  become: true
  file:
    path: "{{ goss_test_directory }}"
    state: directory
    owner: "{{ goss_user }}"
    group: "{{ goss_user }}"
    mode: "{{ goss_test_directory_mode }}"
  tags:
    - goss

- name: Copy render-goss to remote
  become: true
  template:
    src: render-goss
    dest: /usr/local/bin
    owner: "{{ goss_user }}"
    group: "{{ goss_group }}"
    mode: 0750
  tags:
    - goss

- name: Copy Goss template to remote
  become: true
  template:
    src: test_goss.yaml
    dest: "{{ goss_test_directory }}/"
    owner: "{{ goss_user }}"
    group: "{{ goss_group }}"
    mode: 0644
  notify: goss
  tags:
    - goss
...
