---

driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
lint: |
  set -e
  yamllint .
  ansible-lint
  ansible-later
platforms:
  - name: localhost
provisioner:
  name: ansible
verifier:
  name: ansible
