# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox"

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end
  config.ssh.forward_agent = false
  config.ssh.insert_key = false
  # Timeouts
  config.vm.graceful_halt_timeout=30

  config.vm.define :windows2022, primary: true, autostart: true do |win2022|
    win2022.vm.boot_timeout = 3600
    win2022.vm.box =  "jborean93/WindowsServer2022"
    win2022.vm.communicator = "winrm"
    win2022.vm.guest = :windows
    win2022.vm.hostname = "windows2022"
    win2022.vm.network :forwarded_port, guest: 22, host: 2216, id: 'ssh', auto_correct: true
    win2022.vm.network :forwarded_port, guest: 3389, host: 3389, id: 'rdp', auto_correct: true
    win2022.vm.network :forwarded_port, guest: 5985, host: 45985, id: 'winrm', auto_correct: false
    win2022.vm.network :forwarded_port, guest: 5986, host: 45986, id: 'winrms', auto_correct: false
    win2022.vm.network "private_network", ip: "192.168.56.19", :netmask => "255.255.255.0",  auto_config: true
    win2022.winrm.password = "vagrant"
    win2022.winrm.username = "vagrant"
    win2022.vm.provider "virtualbox" do |vb|
      vb.default_nic_type = "virtio"
      vb.cpus = 4
      vb.customize [
        "modifyvm", :id,
        "--audio", "none",
        "--graphicscontroller", "VBoxSVGA",
        "--memory", "4096",
        "--natdnshostresolver1", "on",
        "--cableconnected1", "on",
      ]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
      vb.gui = true
      vb.name = "windows2022"
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "playbook.yml"
    ansible.galaxy_roles_path = "roles"
    ansible.verbose = "vv"
  end
end
