#!/usr/bin/env ansible-playbook
---

- hosts: local
  connection: local
  gather_facts: false
  tasks:
    - name: Clone repository
      git:
        repo: 'git@github.com:ansiblebook/mezzanine_example.git'
        dest: /tmp/mezzanine_example
        version: master
        accept_hostkey: true
        update: false
...
