version: "3.9"

services:
  db:
    image: postgres:15-alpine
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - init.sql:/docker-entrypoint-initdb.d/

  app:
    image: mezzanine:latest
    depends_on:
      - db
    env_file: .env
    volumes:
      - static_data:/app/myproject/static

  nginx:
    image: nginx:alpine
    env_file: .env
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - static_data:/app/myproject/static:ro
      - nginx.conf:/etc/nginx/nginx.conf
