name: Build Ansible-Runner with PyInstaller

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          python -m pip install --upgrade wheel
          python -m pip install --upgrade pyinstaller
          python -m pip install --upgrade ansible-builder

      - name: Build with PyInstaller
        working-directory: c01-introduction/ansible-runner
        run: pyinstaller --clean build-ansible-runner.spec

      - name: Build play.py binary
        run: |
          pyinstaller --onefile play.py --name play

      - name: Archive build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ansible-runner-dist
          path: c01-introduction/ansible-runner/dist/

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/ansible-runner-v')
        uses: softprops/action-gh-release@v2
        with:
          name: "Ansible Runner ${{ github.ref_name }}"
          tag_name: ${{ github.ref_name }}
          files: ansible-runner/dist/ansible-runner/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
